"""initial

Revision ID: 66d901937a71
Revises: 
Create Date: 2025-09-30 15:39:54.159329
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66d901937a71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_at', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.String(length=64), nullable=True),
    sa.Column('nutrition_goal', sa.String(length=64), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('budget_range', sa.String(length=64), nullable=True),
    sa.Column('cooking_time_preference', sa.String(length=64), nullable=True),
    sa.Column('dietary_restrictions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_cuisines', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###
